# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Towards Data Science
tagline:             ' My data science journey'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             '/DSBlog'
paginate:            5

# About/contact
author:
  name:              Priyanka Sabale
  email:             sabale.priyanka@gmail.com

# Custom vars
version:             1.0.0
